// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Zxf_uWrwC2IufNIit4h94c7goYSOpHw',
    appId: '1:801846557581:android:7706abe24f2dde40725bc4',
    messagingSenderId: '801846557581',
    projectId: 'orderapp-bcea2',
    storageBucket: 'orderapp-bcea2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxx3FShL0LN9ah5o0I0DuxOoqDq7B00-A',
    appId: '1:801846557581:ios:edbce994d0f6c1e9725bc4',
    messagingSenderId: '801846557581',
    projectId: 'orderapp-bcea2',
    storageBucket: 'orderapp-bcea2.firebasestorage.app',
    iosBundleId: 'com.example.orderApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxx3FShL0LN9ah5o0I0DuxOoqDq7B00-A',
    appId: '1:801846557581:ios:edbce994d0f6c1e9725bc4',
    messagingSenderId: '801846557581',
    projectId: 'orderapp-bcea2',
    storageBucket: 'orderapp-bcea2.firebasestorage.app',
    iosBundleId: 'com.example.orderApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0iDO0BU6wfuKha1ISiLIMrU3P8_uVKo',
    appId: '1:801846557581:web:eb8c3b2eb7c43ec7725bc4',
    messagingSenderId: '801846557581',
    projectId: 'orderapp-bcea2',
    authDomain: 'orderapp-bcea2.firebaseapp.com',
    storageBucket: 'orderapp-bcea2.firebasestorage.app',
    measurementId: 'G-FZ5SGKNG52',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD0iDO0BU6wfuKha1ISiLIMrU3P8_uVKo',
    appId: '1:801846557581:web:c6437fdb85168825725bc4',
    messagingSenderId: '801846557581',
    projectId: 'orderapp-bcea2',
    authDomain: 'orderapp-bcea2.firebaseapp.com',
    storageBucket: 'orderapp-bcea2.firebasestorage.app',
    measurementId: 'G-KNH3LNHBJ8',
  );
}
